# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - line_length
  - cyclomatic_complexity
  - force_try
  - file_length
  - valid_docs

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods

type_body_length:
  - 400 # warning
  - 500 # error
