disabled_rules:
  - trailing_whitespace
  - line_length
  - function_parameter_count
  - file_length
  - valid_docs
  - vertical_whitespace
  - for_where

opt_in_rules:
 - force_unwrapping

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods

type_body_length:
  warning: 400
  error: 500

variable_name:
  min_length:
    warning: 2
    error: 2
