# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - line_length
  - cyclomatic_complexity
  - force_try
  - file_length
  - valid_docs
  - vertical_whitespace

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Carthage
  - Pods

type_body_length:
  warning: 400
  error: 500

variable_name:
  min_length:
    warning: 2
    error: 2

function_parameter_count:
  warning: 10
  error: 15
